### PR TITLE
Openldap stack ha v4.1.1

### PR DESCRIPTION
**Pull request by fffialho**
### PR Description
Adds a new OpenLDAP chart based on bitnami's OpenLDAP docker image. 
It's based on https://github.com/jp-gouin/helm-openldap/tree/v4.1.1, with some additions:

* Allow adding a CA Certificate to use along side to the Custom TLS  certificate
  * This is useful when certmanager is in use, since it doesn't adds the CA Cert as part of the secret holding the managed cert and key; 
* To workaround an issue with helm downloading dependencies, we have included the bitnami's common helm as part of this helm.

### Checklist

 - [ ] Have you reviewed and updated the chart default values if necessary?
 - [ ] Have you reviewed and updated the chart documentation if necessary?
 - [ ] Does your branch follow the naming convention of `{chartNameWithDashes}-v{versionString}-{optionalPatchVersion}`?
 - [ ] Have you bumped the version in the chart's `Chart.yaml`?

### Tagged Releases
Please remember to make a tagged release after merging your PR that:

 - Has a tag name that matches your PR branch name (see above)
 - Has a description that summarizes the changes made

This makes it possible to use previous versions of the charts maintained here as new releases are published. Please see the release history of this repository for examples.

### CODE REVIEW

**Comment by fffialho** [comment]
Here goes the diff:

```diff
diff --color -NurbBw -x charts -x .git -x .github ./Chart.lock /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/Chart.lock
--- ./Chart.lock	2023-06-22 16:16:04
+++ /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/Chart.lock	2023-06-19 19:47:08
@@ -1,12 +1,12 @@
 dependencies:
 - name: ltb-passwd
-  repository: ""
-  version: 0.1.x
+  repository: file://charts/ltb-passwd
+  version: 0.1.0
 - name: phpldapadmin
-  repository: ""
-  version: 0.1.x
+  repository: file://charts/phpldapadmin
+  version: 0.1.2
 - name: common
-  repository: https://charts.bitnami.com/bitnami
-  version: 1.10.0
-digest: sha256:ffce1e1b35fc49ce33dbf5c063be307964ca75ba6f13d325d32b474ba34c7ea3
-generated: "2021-10-24T14:53:55.640745+02:00"
+  repository: file://charts/common
+  version: 1.10.4
+digest: sha256:cae79bcb5a3899fdbadc55f000ed685a471460af28f65161ad2971bb5e047780
+generated: "2023-06-19T19:47:08.701015-03:00"
diff --color -NurbBw -x charts -x .git -x .github ./Chart.yaml /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/Chart.yaml
--- ./Chart.yaml	2023-06-22 16:16:04
+++ /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/Chart.yaml	2023-06-19 19:45:17
@@ -2,16 +2,16 @@
 name: openldap-stack-ha
 dependencies:
   - name: ltb-passwd
+    repository: "file://charts/ltb-passwd"
     version: 0.1.x
     condition: ltb-passwd.enabled
   - name: phpldapadmin
+    repository: "file://charts/phpldapadmin"
     version: 0.1.x
     condition: phpldapadmin.enabled
   - name: common
-    repository: https://charts.bitnami.com/bitnami
-    tags:
-      - bitnami-common
-    version: 1.x.x
+    repository: "file://charts/common"
+    version: 1.10.x
 home: https://www.openldap.org
 version: 4.1.1
 appVersion: 2.6.3
diff --color -NurbBw -x charts -x .git -x .github ./templates/secret-customTLS-ca.yaml /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/templates/secret-customTLS-ca.yaml
--- ./templates/secret-customTLS-ca.yaml	1969-12-31 21:00:00
+++ /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/templates/secret-customTLS-ca.yaml	2023-05-26 08:48:23
@@ -0,0 +1,18 @@
+{{ if and .Values.customTLS.enabled .Values.customTLS.caPEMContent  }}
+apiVersion: v1
+kind: Secret
+metadata:
+  name: {{ template "openldap.fullname" . }}-customtls-ca
+  labels:
+    app: {{ template "openldap.name" . }}
+    chart: {{ template "openldap.chart" . }}
+    release: {{ .Release.Name }}
+    heritage: {{ .Release.Service }}
+{{- if .Values.extraLabels }}
+{{ toYaml .Values.extraLabels | indent 4 }}
+{{- end }}
+type: Opaque
+data:
+  ca.crt: |-
+{{ .Values.customTLS.caPEMContent | b64enc | indent 4 }}
+{{ end }}
diff --color -NurbBw -x charts -x .git -x .github ./templates/statefulset.yaml /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/templates/statefulset.yaml
--- ./templates/statefulset.yaml	2023-06-22 16:16:04
+++ /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/templates/statefulset.yaml	2023-05-26 08:45:15
@@ -53,12 +53,22 @@
               cp /tmp-certs/tls.crt /tmp-certs/ca.crt
               chmod 777  /tmp-certs/*
               {{- end }}
-              cp -Lr /tmp-certs/* /certs
+              cp -vLr /tmp-certs/* /certs
+              {{- if .Values.customTLS.caPEMContent }}
+              cp -vLr /tmp-certs-ca/* /certs
+              {{- end }}
+          {{- if .Values.customTLS.resources }}
+          resources: {{- toYaml .Values.customTLS.resources | nindent 12 }}
+          {{- end }}
           volumeMounts:
             - name: certs
               mountPath: "/certs"
             - name: secret-certs
               mountPath: "/tmp-certs"
+            {{- if .Values.customTLS.caPEMContent }}
+            - name: secret-certs-ca
+              mountPath: "/tmp-certs-ca"
+            {{- end }}
       {{- if .Values.volumePermissions.enabled }}
         - name: volume-permissions
           image: {{ include "openldap.initContainerImage" . }}
@@ -275,6 +285,11 @@
         - name: secret-certs
           secret:
             secretName: {{ .Values.customTLS.secret }}
+{{- if .Values.customTLS.caPEMContent }}
+        - name: secret-certs-ca
+          secret:
+            secretName: {{ template "openldap.fullname" . }}-customtls-ca
+{{- end }}
 {{- else }}
         - name: secret-certs
           emptyDir:
diff --color -NurbBw -x charts -x .git -x .github ./values.yaml /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/values.yaml
--- ./values.yaml	2023-06-22 16:16:04
+++ /Users/fffialho/src/power/helm-charts/charts/openldap-stack-ha/values.yaml	2023-05-26 09:12:39
@@ -69,6 +69,12 @@
     repository: alpine/openssl
     tag: latest
   secret: ""  # The name of a kubernetes.io/tls type secret to use for TLS
+  # Sometimes it can be useful to inject a custom CA file. When using certmanager is one situation.
+  caPEMContent: ""
+    # |-
+    # -----BEGIN CERTIFICATE-----
+    # PEM data
+    # -----END CERTIFICATE-----
 ## Add additional labels to all resources
 extraLabels: {}

```

**Comment by benlangfeld** [comment]
If this is a fork, why don't we put this in a repo of its own which is actually a fork of the upstream?

**Comment by benlangfeld** [comment]
https://github.com/powerhome/helm-openldap

**Comment by fffialho** [comment]
> If this is a fork, why don't we put this in a repo of its own which is actually a fork of the upstream?

Fair enough. Closing this PR and working on applying the changes in the forked repo.

**Comment by fffialho** [comment]
Fair enough. Closing this PR and working on applying the changes in the forked repo:  https://github.com/powerhome/helm-openldap

**Pull request closed without merging**
